spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_mvc
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  mvc:
    throw-exception-if-no-handler-found: true
    hiddenmethod:
      filter:
        enabled: true
  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true